# Generated by Django 5.1.5 on 2026-05-05 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_plan_enterprise'),
        ('ingest', '0007_wikichangeset_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('url', 'URL'), ('youtube', 'YouTube'), ('markdown', 'Markdown'), ('image', 'Image'), ('repo', 'Repository'), ('code_zip', 'Code Zip')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='raw_sources/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('extracted_text', models.TextField(blank=True)),
                ('structure_map', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingest_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_source', to='ingest.ingestjob')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_sources', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiSourceCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wiki_section', models.CharField(blank=True, help_text='Section heading in wiki page', max_length=300)),
                ('wiki_char_start', models.IntegerField(default=0)),
                ('wiki_char_end', models.IntegerField(default=0)),
                ('source_char_start', models.IntegerField(default=0)),
                ('source_char_end', models.IntegerField(default=0)),
                ('source_page_number', models.IntegerField(blank=True, help_text='For PDFs', null=True)),
                ('source_timestamp', models.CharField(blank=True, help_text='For YouTube, e.g. 02:15', max_length=20)),
                ('source_section', models.CharField(blank=True, help_text='Section heading in raw source', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ingest.rawsource')),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_citations', to='wiki.wikipage')),
            ],
            options={
                'ordering': ['wiki_char_start'],
            },
        ),
    ]
