# Generated by Django 5.1.5 on 2026-05-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_ingestjob_progress_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsource',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
