# Generated by Django 5.1.5 on 2026-05-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_rawsource_source_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='staging_data',
            field=models.BinaryField(blank=True, help_text='Used for Heroku ephemeral storage workaround.', null=True),
        ),
    ]
