# Generated by Django 5.1.5 on 2026-05-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubscription',
            name='grace_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamsubscription',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamsubscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('trial_expired', 'Trial Expired'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='trialing', max_length=30),
        ),
    ]
