# Generated by Django 5.1.5 on 2026-05-12 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_plan_enterprise'),
        ('chat', '0005_agentmemory_ttl_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.TextField(help_text='The user message or event that initiated this episode')),
                ('plan', models.JSONField(blank=True, default=dict, help_text='The approach the agent planned')),
                ('actions', models.JSONField(default=list, help_text='Tool calls executed in order')),
                ('outcome', models.JSONField(default=dict, help_text='Success/failure metrics and results')),
                ('learnings', models.TextField(blank=True, help_text='Extracted lessons for future recall')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Semantic tags for retrieval')),
                ('success', models.BooleanField(default=True)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Total execution time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='chat.chatsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_episodes', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', '-created_at'], name='chat_agente_team_id_b17af1_idx'), models.Index(fields=['team', 'success'], name='chat_agente_team_id_06098c_idx')],
            },
        ),
    ]
