# Generated by Django 5.1.5 on 2026-05-21 20:27

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_plan_enterprise'),
        ('chat', '0006_add_agent_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentepisode',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Pre-computed embedding for semantic recall', null=True),
        ),
        migrations.CreateModel(
            name='MCPServerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Short identifier e.g. 'github', 'slack'", max_length=100)),
                ('url', models.URLField(help_text='MCP server endpoint URL')),
                ('auth_token', models.TextField(blank=True, default='', help_text='Bearer token for server auth')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='List of capability strings')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='accounts.team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
