# Generated by Django 5.1.5 on 2026-06-03 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_team_plan_auto_apply_safe'),
        ('chat', '0007_agentepisode_embedding_mcpserverregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduralMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directive', models.TextField()),
                ('directive_type', models.CharField(choices=[('planning_heuristic', 'Planning Heuristic'), ('integration_rule', 'Integration Rule'), ('communication_style', 'Communication Style'), ('risk_pattern', 'Risk Pattern'), ('workflow_preference', 'Workflow Preference'), ('vocabulary', 'Vocabulary'), ('failure_pattern', 'Failure Pattern'), ('success_pattern', 'Success Pattern')], max_length=50)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('applicable_intent_types', models.JSONField(blank=True, default=list)),
                ('source_episode_ids', models.JSONField(blank=True, default=list)),
                ('extraction_method', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.7)),
                ('reinforcement_count', models.IntegerField(default=1)),
                ('contradiction_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_reinforced_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-confidence', '-reinforcement_count'],
            },
        ),
        migrations.AddField(
            model_name='agentepisode',
            name='error_trace',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agentepisode',
            name='failure_point',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agentepisode',
            name='inferred_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentepisode',
            name='quality_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='agentepisode',
            name='rounds_taken',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='agentepisode',
            index=models.Index(fields=['inferred_domain'], name='chat_agente_inferre_11b69a_idx'),
        ),
        migrations.AddField(
            model_name='proceduralmemory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedural_memories', to='accounts.team'),
        ),
        migrations.AddIndex(
            model_name='proceduralmemory',
            index=models.Index(fields=['team', 'domain', 'directive_type'], name='chat_proced_team_id_bc13e0_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduralmemory',
            index=models.Index(fields=['team', 'applicable_intent_types'], name='chat_proced_team_id_c524cb_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduralmemory',
            index=models.Index(fields=['confidence', 'reinforcement_count'], name='chat_proced_confide_514852_idx'),
        ),
    ]
