# Generated by Django 5.1.5 on 2026-06-03 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_team_plan_auto_apply_safe'),
        ('chat', '0008_procedural_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentClassificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('message_hash', models.CharField(db_index=True, max_length=64)),
                ('intent_type', models.CharField(max_length=100)),
                ('complexity', models.CharField(max_length=20)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('required_capabilities', models.JSONField(blank=True, default=list)),
                ('intent_confidence', models.FloatField()),
                ('layer_used', models.IntegerField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.IntegerField()),
                ('agent_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('crew_used', models.BooleanField(default=False)),
                ('crew_composition', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_classification_logs', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'intent_type', 'created_at'], name='chat_intent_team_id_ad105b_idx'), models.Index(fields=['layer_used', 'created_at'], name='chat_intent_layer_u_ee7388_idx')],
            },
        ),
    ]
