# Generated by Django 5.1.5 on 2026-06-03 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_team_plan_auto_apply_safe'),
        ('chat', '0009_intent_classification_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserverregistration',
            name='allowed_crew_roles',
            field=models.JSONField(blank=True, help_text="Crew roles allowed to call this server's tools. Null = all roles.", null=True),
        ),
        migrations.AddField(
            model_name='mcpserverregistration',
            name='risk_level_override',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MCPRegistrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_events', to='chat.mcpserverregistration')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MCPToolExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('server_name', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_input', models.JSONField(default=dict)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('circuit_state_at_call', models.CharField(blank=True, max_length=20, null=True)),
                ('idempotency_hit', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_logs', to='accounts.team')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['team', 'server_name', 'timestamp'], name='chat_mcptoo_team_id_b1b53d_idx'), models.Index(fields=['tool_name', 'success'], name='chat_mcptoo_tool_na_0a2bbe_idx')],
            },
        ),
    ]
