# Generated by Django 5.1.5 on 2026-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_task_parent_task_notification_taskcomment'),
        ('wiki', '0006_add_project_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_wiki_pages',
            field=models.ManyToManyField(blank=True, help_text='Wiki pages/documents semantically linked to this project.', related_name='associated_projects', to='wiki.wikipage'),
        ),
    ]
