# Generated by Django 5.1.5 on 2026-06-01 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_safe_plan_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_overdue', 'Task Overdue'), ('task_due_today', 'Task Due Today'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('milestone_missed', 'Milestone Missed'), ('milestone_approaching', 'Milestone Approaching'), ('milestone_reached', 'Milestone Reached'), ('conflict_detected', 'Conflict Detected'), ('integration_synced', 'Integration Synced'), ('mention', 'Mention')], max_length=50),
        ),
        migrations.CreateModel(
            name='CanvasLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('viewport', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas', to='planning.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_canvases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canvas Layout',
            },
        ),
        migrations.CreateModel(
            name='ProjectIntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_calendar_sync', models.BooleanField(default=True)),
                ('auto_slack_notify', models.BooleanField(default=False)),
                ('auto_github_issues', models.BooleanField(default=False)),
                ('auto_jira_issues', models.BooleanField(default=False)),
                ('auto_linear_issues', models.BooleanField(default=False)),
                ('slack_channel', models.CharField(blank=True, max_length=100)),
                ('github_repo', models.CharField(blank=True, max_length=200)),
                ('jira_project_key', models.CharField(blank=True, max_length=20)),
                ('linear_team_id', models.CharField(blank=True, max_length=50)),
                ('notify_on_assign', models.BooleanField(default=True)),
                ('notify_on_overdue', models.BooleanField(default=True)),
                ('notify_on_complete', models.BooleanField(default=False)),
                ('notify_on_milestone', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_config', to='planning.project')),
            ],
            options={
                'verbose_name': 'Project Integration Config',
            },
        ),
        migrations.CreateModel(
            name='IntegrationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('calendar_create', 'Calendar Event Created'), ('calendar_update', 'Calendar Event Updated'), ('calendar_delete', 'Calendar Event Deleted'), ('slack_notify', 'Slack Message Sent'), ('github_issue', 'GitHub Issue Created'), ('jira_issue', 'Jira Issue Created'), ('linear_issue', 'Linear Issue Created'), ('notion_page', 'Notion Page Created'), ('gmail_reminder', 'Gmail Reminder Sent')], max_length=30)),
                ('provider', models.CharField(max_length=30)),
                ('external_ref', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_actions', to='planning.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'action'], name='planning_in_entity__0d5c1d_idx')],
            },
        ),
    ]
