# Generated by Django 5.1.5 on 2026-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_add_canvas_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='langgraph_thread_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planning_run_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
