# Generated by Django 5.1.5 on 2026-06-03 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_team_plan_auto_apply_safe'),
        ('planning', '0012_project_langgraph_thread_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_input', models.JSONField()),
                ('tool_result', models.JSONField(blank=True, null=True)),
                ('tier', models.IntegerField()),
                ('approved', models.BooleanField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('agent_round', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_audit_logs', to='accounts.team')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['team', 'timestamp'], name='planning_gu_team_id_281eb2_idx'), models.Index(fields=['tool_name', 'approved'], name='planning_gu_tool_na_269fa7_idx'), models.Index(fields=['session_id'], name='planning_gu_session_60dabe_idx')],
            },
        ),
    ]
