# Generated by Django 6.0.4 on 2026-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='auto_approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingestjob',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='source_type',
            field=models.CharField(choices=[('url', 'URL'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('markdown', 'Markdown'), ('repo', 'Repository')], max_length=20),
        ),
    ]
