# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0006_ingestjob_staging_youtube_image_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikichangeset",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wikichangeset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
