# Generated by Django 5.1.5 on 2026-05-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_rawsource_wikisourcecitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestjob',
            name='progress_pct',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
