# Generated by Django 5.1.5 on 2026-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_ingestjob_progress_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsource',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
