# Generated by Django 5.1.5 on 2026-06-01 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('external_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('external_user_name', models.CharField(blank=True, default='', max_length=255)),
                ('external_user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='integrations.userintegration')),
            ],
        ),
        migrations.CreateModel(
            name='ToolExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('tool_name', models.CharField(max_length=150)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_logs', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_logs', to='integrations.userintegration')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='integration_user_id_ff0ac8_idx'), models.Index(fields=['provider', '-timestamp'], name='integration_provide_e7cd71_idx')],
            },
        ),
    ]
