# Generated by Django 5.1.5 on 2026-05-05 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_plan_enterprise'),
        ('chat', '0003_chatmessage_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='e.g. current_priorities, known_blockers', max_length=200)),
                ('category', models.CharField(choices=[('priorities', 'Current Priorities'), ('blockers', 'Known Blockers'), ('gaps', 'Knowledge Gaps'), ('decisions', 'Recent Decisions'), ('contradictions', 'Active Contradictions'), ('context', 'General Context')], default='context', max_length=30)),
                ('value', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary of this memory entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to='accounts.team')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('team', 'key')},
            },
        ),
    ]
