# Generated by Django 5.1.5 on 2026-05-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_agentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='ttl_days',
            field=models.PositiveIntegerField(default=30, help_text='Days until this memory expires'),
        ),
    ]
