# Generated by Django 5.1.5 on 2026-05-07 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_team_plan_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamApiUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(help_text='e.g. chat_ask, chat_agent, ingest_decompose, etc.', max_length=60)),
                ('model_used', models.CharField(max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('value_score', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('billing_month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('routed_by', models.CharField(choices=[('free_fixed', 'Free Fixed'), ('continuous_curve', 'Continuous Curve'), ('enterprise_sla', 'Enterprise SLA')], default='continuous_curve', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='accounts.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'billing_month'], name='llm_orchest_team_id_f18e46_idx'), models.Index(fields=['user', 'billing_month'], name='llm_orchest_user_id_268816_idx')],
            },
        ),
    ]
