# Generated by Django 5.1.5 on 2026-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamapiusage',
            name='routed_by',
            field=models.CharField(choices=[('free_fixed', 'Free Fixed'), ('continuous_curve', 'Continuous Curve'), ('grace_period_fallback', 'Grace Period Fallback'), ('value_aware_priority', 'Value-Aware Priority'), ('pro_background_routing', 'Pro Background Routing'), ('team_background_routing', 'Team Background Routing'), ('cache', 'Cache Hit'), ('enterprise_sla', 'Enterprise SLA')], default='continuous_curve', max_length=30),
        ),
    ]
