# Generated by Django 5.1.5 on 2026-05-10 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_planchunk_embedding_remove_planchunk_qdrant_point_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('agent', 'Agent')], default='auto', max_length=20)),
                ('data', models.JSONField(help_text='JSON of full project state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='planning.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
