# Generated by Django 6.0.4 on 2026-04-30 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_type', models.CharField(default='standard', max_length=30)),
                ('default_content', models.TextField()),
                ('default_frontmatter', models.JSONField(default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('page_type', models.CharField(choices=[('standard', 'Standard'), ('decision', 'Decision Record'), ('meeting', 'Meeting Notes'), ('brief', 'Project Brief'), ('incident', 'Incident Report'), ('sop', 'SOP')], default='standard', max_length=30)),
                ('frontmatter', models.JSONField(blank=True, default=dict)),
                ('raw_file_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='accounts.team')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('team', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PageChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('qdrant_point_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='wiki.wikipage')),
            ],
            options={
                'ordering': ['chunk_index'],
                'unique_together': {('page', 'chunk_index')},
            },
        ),
    ]
