# Generated by Django 6.0.4 on 2026-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='raw_content',
            field=models.TextField(blank=True),
        ),
    ]
