# Generated by Django 6.0.4 on 2026-05-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_projectmember'),
        ('wiki', '0002_wikipage_raw_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='project',
            field=models.OneToOneField(blank=True, help_text='The strategic plan this page represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_page', to='planning.project'),
        ),
    ]
