# Generated by Django 5.1.5 on 2026-05-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_pagechunk_embedding_remove_pagechunk_qdrant_point_id'),
    ]

    operations = [
    ]
