# Generated by Django 5.1.5 on 2026-05-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='researchlog',
            new_name='research_re_team_id_8850c4_idx',
            old_name='researchlo_team_id_8c03d9_idx',
        ),
        migrations.RenameIndex(
            model_name='researchlog',
            new_name='research_re_action_ea0047_idx',
            old_name='researchlo_action_c7aab8_idx',
        ),
    ]
