import type { PlanProjectDetail } from "../types";

export function exportPlanToHTML(project: PlanProjectDetail) {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${project.name} - Roadmap</title>
  <style>
    body { font-family: sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 0 20px; }
    h1 { border-bottom: 2px solid #00d4e8; padding-bottom: 10px; color: #020204; }
    h2 { color: #00d4e8; margin-top: 30px; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 20px; }
    .task { border-left: 4px solid #eee; padding: 15px; margin-bottom: 10px; background: #f9f9f9; }
    .task.high { border-left-color: #ff3366; }
    .task.completed { opacity: 0.6; }
    .task-title { font-weight: bold; margin-bottom: 5px; }
    .milestone { background: #e0faff; padding: 15px; border-radius: 8px; margin-bottom: 10px; }
    .date { font-weight: bold; font-family: monospace; }
    .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 0.75em; text-transform: uppercase; font-weight: bold; background: #eee; }
  </style>
</head>
<body>
  <h1>${project.name}</h1>
  <p>${project.description || "No description provided."}</p>
  <div class="meta">
    Status: <strong>${project.status}</strong> | 
    Created: ${new Date(project.created_at).toLocaleDateString()}
  </div>

  <h2>Strategic Roadmap</h2>
  ${project.tasks
    .map(
      (t) => `
    <div class="task ${t.priority} ${t.status}">
      <div class="task-title">${t.title} <span class="badge">${t.priority}</span></div>
      <div>${t.description || ""}</div>
      <div class="meta">Timeline: ${t.start_date || "?"} to ${t.end_date || "?"} | Status: ${t.status}</div>
    </div>
  `,
    )
    .join("")}

  <h2>Critical Milestones</h2>
  ${project.milestones
    .map(
      (m) => `
    <div class="milestone">
      <div class="task-title">${m.title}</div>
      <div>${m.description || ""}</div>
      <div class="date">Target: ${m.target_date || "?"}</div>
    </div>
  `,
    )
    .join("")}

  <footer style="margin-top: 50px; font-size: 0.8em; color: #999; text-align: center;">
    Generated by TeamOS PlanArchitect
  </footer>
</body>
</html>
  `;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${project.name.toLowerCase().replace(/\s+/g, "-")}-roadmap.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportPlanToJSON(project: PlanProjectDetail) {
  const data = JSON.stringify(project, null, 2);
  const blob = new Blob([data], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${project.name.toLowerCase().replace(/\s+/g, "-")}-data.json`;
  a.click();
  URL.revokeObjectURL(url);
}
