from django.urls import path

from .views import (
    PlanningCalendarFeedView,
    PlanningMilestoneDetailView,
    PlanningMilestoneListView,
    PlanningProjectDetailView,
    PlanningProjectRemediateView,
    PlanningProjectListView,
    PlanningTaskDetailView,
    PlanningTaskListView,
    PlanningAssistView,
    PlanningAssistStreamView,
    PlanningActivityView,
    PlanningConflictView,
    PlanningRiskView,
    PlanningOverdueView,
    PlanningSnapshotListView,
    PlanningSnapshotRestoreView,
    PlanningVersionListView,
    PlanningVersionRestoreView,
    PlanningChangeSetListView,
    PlanningChangeSetDetailView,
    PlanningChangeSetApproveView,
    PlanningChangeSetRejectView,
    PlanningConflictResolveView,
    PlanningRiskResolveProposalView,
    PlanningRiskResolveApplyView,
    NotificationListView,
    TaskCommentListView,
    PlanningTaskDecomposeDailyView,
)

urlpatterns = [
    path("<uuid:team_id>/projects/", PlanningProjectListView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/", PlanningProjectDetailView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/remediate/", PlanningProjectRemediateView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/tasks/", PlanningTaskListView.as_view()),
    path(
        "<uuid:team_id>/projects/<uuid:project_id>/tasks/<uuid:task_id>/",
        PlanningTaskDetailView.as_view(),
    ),
    path(
        "<uuid:team_id>/projects/<uuid:project_id>/milestones/", PlanningMilestoneListView.as_view()
    ),
    path(
        "<uuid:team_id>/projects/<uuid:project_id>/milestones/<uuid:milestone_id>/",
        PlanningMilestoneDetailView.as_view(),
    ),
    path("<uuid:team_id>/calendar/feed/", PlanningCalendarFeedView.as_view()),
    path("<uuid:team_id>/assist/", PlanningAssistView.as_view()),
    path("<uuid:team_id>/assist/stream/", PlanningAssistStreamView.as_view()),
    path("<uuid:team_id>/activity/", PlanningActivityView.as_view()),
    path("<uuid:team_id>/conflicts/", PlanningConflictView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/conflicts/", PlanningConflictView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/conflicts/resolve/", PlanningConflictResolveView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/risk/", PlanningRiskView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/risk/resolve/proposal/", PlanningRiskResolveProposalView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/risk/resolve/apply/", PlanningRiskResolveApplyView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/snapshots/", PlanningSnapshotListView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/snapshots/<uuid:snapshot_id>/restore/", PlanningSnapshotRestoreView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/versions/", PlanningVersionListView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/versions/<uuid:version_id>/restore/", PlanningVersionRestoreView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/changesets/", PlanningChangeSetListView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/changesets/<uuid:changeset_id>/", PlanningChangeSetDetailView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/changesets/<uuid:changeset_id>/approve/", PlanningChangeSetApproveView.as_view()),
    path("<uuid:team_id>/projects/<uuid:project_id>/changesets/<uuid:changeset_id>/reject/", PlanningChangeSetRejectView.as_view()),
    path("<uuid:team_id>/overdue/", PlanningOverdueView.as_view()),
    path("<uuid:team_id>/notifications/", NotificationListView.as_view()),
    path(
        "<uuid:team_id>/projects/<uuid:project_id>/tasks/<uuid:task_id>/comments/",
        TaskCommentListView.as_view(),
    ),
    path(
        "<uuid:team_id>/projects/<uuid:project_id>/tasks/<uuid:task_id>/decompose-daily/",
        PlanningTaskDecomposeDailyView.as_view(),
    ),
]
