# Generated by Django 6.0.4 on 2026-04-30 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(choices=[('wikilink', 'Wikilink'), ('ai_inferred', 'AI Inferred'), ('manual', 'Manual')], default='wikilink', max_length=30)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_by', models.CharField(default='human', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='wiki.wikipage')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='wiki.wikipage')),
            ],
            options={
                'unique_together': {('from_page', 'to_page', 'edge_type')},
            },
        ),
    ]
