# Generated by Django 6.0.4 on 2026-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphedge',
            name='edge_type',
            field=models.CharField(choices=[('wikilink', 'Wikilink'), ('ai_inferred', 'AI Inferred'), ('manual', 'Manual'), ('citation', 'Citation'), ('semantic', 'Semantic Similarity')], default='wikilink', max_length=30),
        ),
    ]
