# Generated by Django 5.1.5 on 2026-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_engine', '0002_alter_graphedge_edge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphedge',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra context, e.g. conflicting snippets.'),
        ),
        migrations.AddField(
            model_name='graphedge',
            name='reason',
            field=models.TextField(blank=True, help_text='Agent-generated explanation of why this relation exists.'),
        ),
        migrations.AlterField(
            model_name='graphedge',
            name='edge_type',
            field=models.CharField(choices=[('wikilink', 'Wikilink'), ('ai_inferred', 'AI Inferred'), ('manual', 'Manual'), ('citation', 'Citation'), ('semantic', 'Semantic Similarity'), ('depends_on', 'Depends On'), ('contradicts', 'Contradicts'), ('extends', 'Extends'), ('implements', 'Implements'), ('supersedes', 'Supersedes'), ('parent_child', 'Parent-Child'), ('prerequisite', 'Prerequisite'), ('references', 'References')], default='wikilink', max_length=30),
        ),
    ]
